Update patch set 2
Patch Set 2:

Hi Bruno,
I'm using LineageOS on my xiaomi mi5s (and it's wonderful).
Since this commit (at least I suspect), My device began getting error 7 during update process.

Using TWRP 3.2.3-0

Current installed Lineage version on my device: 
15.1-20181117-NIGHTLY-capricorn

Here is the log from my device (TWRP installation truncated log):

"
ERROR: This package requires firmware from MIUI 8.11.8 developer build or newer. Please upgrade firmware and retry!
Updater process ended with ERROR: 7
Error installing zip file '@/cache/recovery/block/map
"

I wouldn't want to downgrade back to miui just to then reinstall LineageOS to enable nightly updates.

Hope you can take care of this.

Patch-set: 2
CC: Tomer Agam <20705@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>